# .github/workflows/debug_setup_python.yml
name: Debug Setup Python

on:
  
  workflow_dispatch:

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: List files after checkout (Manual)
        run: |
          echo "--- Listing files in $(pwd) ---"
          ls -la
          echo "--- Finding pyproject.toml ---"
          find . -name pyproject.toml
          echo "--- End Listing ---"

      - name: Set up Python (Attempting cache check)
        uses: actions/setup-python@v5
        id: setup_python # Give it an ID
        continue-on-error: true 
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'

      
      - name: Check setup-python result
        run: |
          echo "Setup Python step outcome: ${{ steps.setup_python.outcome }}"
           